### ISSUE TITLE
upgrade to 3.0.1 calling `EasyLoading.show` shows a error: `Null check operator used on a null value`

### ISSUE THREAD

**Issue by Muzm** [nslog11/flutter_easyloading#125]
accroding to [this](https://github.com/nslog11/flutter_easyloading/issues/123#issuecomment-908832707) . I upgrade `flutter_easyloading: 3.0.0` to `3.0.1`. and call `EasyLoading.show();`, My page become flutter red error screen and a error shows: 
``` bash
Null check operator used on a null value

The relevant error-causing widget was: 
  GestureDetector file:///Users/.../main.dart:192:14
When the exception was thrown, this was the stack: 
#0      EasyLoadingTheme.boxShadow (package:flutter_easyloading/src/theme.dart:59:43)
#1      _Indicator.build (package:flutter_easyloading/src/widgets/container.dart:198:37)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:4648:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
...
```
`flutter_easyloading/src/theme.dart:59`: 
``` dart
/// boxShadow color of loading
  static List<BoxShadow>? get boxShadow =>
      EasyLoading.instance.loadingStyle == EasyLoadingStyle.custom
          ? EasyLoading.instance.boxShadow! // error because added "!" ?
          : null;
```

**Flutter/Dart info**
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)

**Comment by nslog11** [comment]
please update to v3.0.2

**Comment by Muzm** [comment]
In 3.0.2 `flutter_easyloading/src/theme.dart:59`

```dart 
  /// boxShadow color of loading
  static List<BoxShadow>? get boxShadow =>
      EasyLoading.instance.loadingStyle == EasyLoadingStyle.custom
          ? EasyLoading.instance.boxShadow ?? BoxShadow() 
          : null;
```
The `boxShadow` getter return value types is `null` or `BoxShadow`, not as expect `List<BoxShadow>`.  correct code should be this:

``` dart
  /// boxShadow color of loading
  static List<BoxShadow>? get boxShadow =>
      EasyLoading.instance.loadingStyle == EasyLoadingStyle.custom
          ? EasyLoading.instance.boxShadow ?? [BoxShadow()] // List<BoxShadow> : [BoxShadow()]
          : null;
```
